#!/bin/bash

set -u
set -e

# The URL to our GitHub project
gitProject='https://github.com/devops-workflow'
# Clones from $gitProject are stored under this directory
gitDir='/root'
puppetEnvironment='production'

roles=$@
currentDir=$(pwd)

Fail() {
  echo "$@"
  exit 1
}

YumInstall() {
  package="$1"
  yum --nogpgcheck -y install "$package"
}

if [ ! -d "$gitDir" ]
then
  if [ -e "$gitDir" ]
  then
    Fail "$gitDir exists, but it isn't a directory"
  else
    mkdir -p "$gitDir"
  fi
fi
PullProjectRepo() {
  repo="$1"
  gitPath="${gitProject}/${repo}.git"
  echo "Taking latest from $gitPath"
  if [ -d "${gitDir}/${repo}" ]
  then
    cd "${gitDir}/${repo}" && git pull
    cd "$currentDir"
  else
    git clone "$gitPath" "${gitDir}/${repo}"
  fi
}

RedHat() {
  echo -e "[puppet-products]\nname=puppet-products\nbaseurl=http://yum.puppetlabs.com/el/\$releasever/products/\$basearch\ngpgcheck=0\nenabled=1" > /etc/yum.repos.d/puppet.repo
  echo -e "[puppet-dependencies]\nname=puppet-dependencies\nbaseurl=http://yum.puppetlabs.com/el/\$releasever/dependencies/\$basearch\ngpgcheck=0\nenabled=1" >> /etc/yum.repos.d/puppet.repo
  YumInstall git
  YumInstall puppet-3.8.1
}

if [ -f '/etc/debian_version' ]
then
  osfamily='Debian'
elif [ -f '/etc/redhat-release' ]
then
  osfamily='RedHat'
fi

set +e
grep -q ^10\.1\.1\.4 /etc/hosts
if [ $? -eq 1 ]
then
  echo -n "10.1.1.4\tpuppet" >> /etc/hosts
fi
set -e

case $osfamily in
  RedHat)
    RedHat
  ;;
  Debian)
    Debian
  ;;
  *)
    Fail "Unsupported OS."
  ;;
esac

for role in ${roles[@]}
do
  echo "Inclding $role role"
  . /vagrant/box-scripts/${role}
done
