#!/bin/bash

# Pull/run r10k
if [ -d "${gitDir}/puppet-r10k" ]
then
  PullProjectRepo "puppet-r10k"
else
  PullProjectRepo "puppet-r10k"
  ${gitDir}/puppet-r10k/install.sh
fi

puppet apply /etc/puppet/environments/${puppetEnvironment}/manifests/site.pp "--modulepath=/etc/puppet/environments/${puppetEnvironment}/modules"
